---
- name: Check if Tigera operator is already installed
  ansible.builtin.command:
    cmd: "{{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config get deploy tigera-operator -n tigera-operator"
  register: tigera_operator_check
  failed_when: tigera_operator_check.rc not in [0, 1]
  changed_when: false
  become: true

- name: Apply Tigera operator manifest if not already installed
  ansible.builtin.command:
    cmd: "{{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config create -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/tigera-operator.yaml"
  register: tigera_operator_result
  retries: 3
  delay: 5
  until: tigera_operator_result.rc == 0
  when: tigera_operator_check.rc == 1
  become: true

- name: Check if Calico custom resources are already installed
  ansible.builtin.command:
    cmd: "{{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config get bgpconfiguration default"
  register: calico_custom_resources_check
  failed_when: calico_custom_resources_check.rc not in [0, 1]
  changed_when: false
  become: true

- name: Apply Calico custom resources manifest if not already installed
  ansible.builtin.command:
    cmd: "{{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config create -f https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/custom-resources.yaml"
  register: calico_custom_resources_result
  retries: 3
  delay: 5
  until: calico_custom_resources_result.rc == 0
  when: calico_custom_resources_check.rc == 1
  become: true

- name: Wait for calico-apiserver deployment to be ready
  ansible.builtin.command: >
    {{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config -n calico-apiserver rollout status deployment/calico-apiserver
  retries: 10
  delay: 30
  register: calico_apiserver_result
  until: calico_apiserver_result.rc == 0

- name: Wait for calico-kube-controllers deployment to be ready
  ansible.builtin.command: >
    {{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config -n calico-system rollout status deployment/calico-kube-controllers
  retries: 10
  delay: 30
  register: calico_kube_controllers_result
  until: calico_kube_controllers_result.rc == 0

- name: Wait for calico-typha deployment to be ready
  ansible.builtin.command: >
    {{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config -n calico-system rollout status deployment/calico-typha
  retries: 10
  delay: 30
  register: calico_typha_result
  until: calico_typha_result.rc == 0

- name: Wait for coredns deployment to be ready
  ansible.builtin.command: >
    {{ k8s_binary_location }}/kubectl --kubeconfig /home/{{ kubernetes_user }}/.kube/config -n kube-system rollout status deployment/coredns
  retries: 10
  delay: 30
  register: coredns_result
  until: coredns_result.rc == 0
