---
- name: Check if K8S CA file exists
  ansible.builtin.stat:
    path: "{{ kubernetes_ca_cert_location }}"
  register: k8s_cert_file

- name: Copy CA file from master
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/ca.crt
    dest: "{{ kubernetes_ca_cert_location }}"
    flat: true
  run_once: true
  delegate_to: "{{ hostvars[groups['kube_masters'][0]].ansible_host }}"
  vars:
    ansible_ssh_user: "{{ hostvars[groups['kube_masters'][0]].ansible_user }}"
    ansible_ssh_private_key_file: "{{ hostvars[groups['kube_masters'][0]].ansible_ssh_private_key_file }}"
  when: not k8s_cert_file.stat.exists
