---
# Defaults
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg

docker_repo: >
  deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg]
  https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

ubuntu_containerd_package: containerd.io

k8s_release_version: v1.30.1
kubernetes_version: "{{ k8s_release_version | regex_replace('^v', '') }}-1.1" # Example 1.30.1-00
kubernetes_gpg_url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_release_version | regex_replace('^(v\\d+\\.\\d+).*', '\\1') }}/deb/Release.key"
kubernetes_repo: >
  deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
  https://pkgs.k8s.io/core:/stable:/{{ k8s_release_version | regex_replace('\.1', '') }}/deb/ /
kubernetes_user: ubuntu

k8s_binary_location: /usr/bin
local_kube_config: /Users/alexanderkalaj/Documents/github/ansible-cncf-k8s-role/roles/ansible-cncf-k8s/config
kubernetes_join_script: /Users/alexanderkalaj/Documents/github/ansible-cncf-k8s-role/roles/ansible-cncf-k8s/kubeadm-join.sh

calico_version: v3.28.2
calico_operator_manifest: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/tigera-operator.yaml"
calico_custom_resources_manifest: "https://raw.githubusercontent.com/projectcalico/calico/v3.28.2/manifests/custom-resources.yaml"
